spring:
  datasource:
    hikari:
      maximum-pool-size: '5'
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: TRACE
        security: DEBUG

