-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tag
(
    id bigserial NOT NULL,
    name character varying(100) UNIQUE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.gift_certificate
(
    id bigserial NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500) NOT NULL,
    price real NOT NULL,
    duration smallint NOT NULL,
    create_date timestamp without time zone NOT NULL,
    last_update_date timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tag_gift_certificate
(
    tag_id bigserial NOT NULL,
    gift_certificate_id bigserial NOT NULL
);

ALTER TABLE public.tag_gift_certificate
    ADD FOREIGN KEY (tag_id)
    REFERENCES public.tag (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;


ALTER TABLE public.tag_gift_certificate
    ADD FOREIGN KEY (gift_certificate_id)
    REFERENCES public.gift_certificate (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
    
CREATE TABLE IF NOT EXISTS public.user
(
    id bigserial NOT NULL,
    user_name character varying(100) UNIQUE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order
(
    id bigserial NOT NULL,
    user_id bigserial NOT NULL,
    gift_certificate_id bigserial NOT NULL,
    cost real NOT NULL,
    purchase_date timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.order
    ADD FOREIGN KEY (user_id)
    REFERENCES public.user (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
    
ALTER TABLE public.order
    ADD FOREIGN KEY (gift_certificate_id)
    REFERENCES public.gift_certificate (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

END;

